#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

/bin/polybar-setup.sh

s1="$(grep = $HOME/.config/polybar/screens.ini | grep screen1 | sed 's/screen1="//' | sed 's/"//' | sed -e 's/^[[:space:]]*//')"
s2="$(grep = $HOME/.config/polybar/screens.ini | grep screen2 | sed 's/screen2="//' | sed 's/"//' | sed -e 's/^[[:space:]]*//')"

if [ s2 != "/dev/null" ]
then
	bspc monitor "$s1" -d I II III IV V
	bspc monitor "$s2" -d VI VII VIII IX X
else
	bspc monitor "$s1" -d I II III IV V
fi

#bspc monitor -d I II III IV V VI VII VIII IX X

#bspc monitor DP-2 -d I II III IV V
#bspc monitor DP-0 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xsetroot -cursor_name left_ptr &
bspc config focus_follows_pointer true
bspc config border_width 0

picom & 
nitrogen --restore &
clipit &
xset dpms 0 0 0 &
xset s off &
pacmd set-sink-volume 0 40000


$HOME/.config/polybar/launch.sh
